# TravisCI config file. See http://travis-ci.org
language: python

python:
  - 2.7

env:
  - B3_REPO='git+git://github.com/BigBrotherBot/big-brother-bot.git@release-1.10#egg=b3'

# command to install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install pytest-cov
  - pip install -r afk/tests/requirements.txt
  - pip install -e ${B3_REPO}

# command to run tests, e.g. python setup.py test
script: PYTHONPATH=extplugins py.test --cov-config .coveragerc --cov=afk --cov-report=term-missing afk/tests

after_success:
  - pip install python-coveralls
  - coveralls